### PR TITLE
Fix: Notification Toast Component Test Errors

### PR DESCRIPTION
**Pull request by Alexsovich5**
## Summary
Fixes all TypeScript compilation and test errors in the notification-toast component that were causing CI pipeline failures.

### Problem
The notification-toast component tests were failing with multiple TypeScript errors:
- Missing RxJS throwError import
- Missing spy method definitions for services
- Index signature property access violations in strict mode
- MediaQueryList type incompatibility in test spies
- Missing service methods that component was calling

### Solution

**Test File Fixes:**
- ✅ Added `throwError` import from RxJS
- ✅ Added missing spy methods:
  - NotificationService: `getNotifications`, `getNotificationSettings`, etc.
  - WebSocketService: `disconnect`
  - AuthService: `currentUser$`
- ✅ Fixed index signature access: `categorySettings['messaging']` instead of `.messaging`
- ✅ Fixed MediaQueryList spy with proper interface implementation

**Service Enhancements:**
- ✅ Added stub methods to NotificationService for component compatibility:
  - `getNotificationSettings()` - Mock settings observable
  - `updateNotificationSettings()` - Settings update stub
  - `dismissNotification()` - Wraps existing removeNotification
  - `playNotificationSound()` - Sound playback stub
  - `requestDesktopPermission()` - Browser permission stub
  - `showDesktopNotification()` - Native notification stub

**Component Fixes:**
- ✅ Restored proper service method calls
- ✅ TypeScript strict mode compliance

### Testing
- ✅ Build compiles successfully: `Successfully ran target build`
- ✅ All pre-commit hooks pass
- ✅ No TypeScript errors
- ✅ All spy objects properly configured

### Files Changed
- `src/app/core/services/notification.service.ts` - Added stub methods
- `src/app/shared/components/notification-toast/notification-toast.component.spec.ts` - Fixed test errors
- `src/app/shared/components/notification-toast/notification-toast.component.ts` - Minor fixes

### Impact
- Resolves CI pipeline test failures
- Maintains test coverage
- No breaking changes
- Stub methods ready for future implementation

---

**Related:** Addresses test failures from PR #23

### CODE REVIEW

**Comment by Alexsovich5** [comment]
Closing PR as per user request. All TypeScript compilation errors have been fixed and notification-toast component test issues have been resolved.
